banking_django_plaid-master/banking_django_plaid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
]

banking_django_plaid-master/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.loginPage, name = 'login'),
    path('logout/', views.logoutUser, name = 'logout'),
    path('home/', views.home, name = 'home'),
    path('account/', views.account, name = 'account'),
    path('submitToken/', views.submitToken, name = 'submitToken'),
    path('getAccountData', views.getAccountData, name = 'getAccountData'),
    path('getTransactionData', views.getTransactionData, name = 'getTransactionData'),
]

banking_django_plaid-master/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tokens(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    access_tkn = models.CharField(max_length = 200, default = None, null=True, blank=True)
    item_id = models.CharField(max_length = 200, default = None, null=True, blank=True)
    webhook = models.CharField(max_length = 200, default = None, null=True, blank=True)

class Account(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=50, default=None, null=True, blank=True)
	official_name = models.CharField(max_length=50, default=None, null=True, blank=True)
	account_id = models.TextField()
	balance_available = models.IntegerField(null=True, default=None)
	balance_current = models.IntegerField(null=True, default=None)
	iso_currency_code = models.CharField(max_length=10, default=None, null=True, blank=True)
	limit = models.IntegerField(default=None, null=True, blank=True)
	sub_type = models.CharField(max_length=10, default=None, null=True, blank=True)
	acc_type = models.CharField(max_length=10, default=None, null=True, blank=True)
	mask = models.CharField(max_length=10, default=None, null=True, blank=True)

banking_django_plaid-master/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


banking_django_plaid-master/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from plaid import Client
from plaid.errors import APIError, ItemError, InvalidInputError, InvalidRequestError
import requests
import json

# Create your views here.
from .forms import UserSignupForm
from .models import Tokens
from .tasks import saveTask

plaid_client_id = "5da9e9d3470e370016651aa3"
plaid_secret = "1026c23bcd23fccd4f9dabb1f9f172"

client = Client(client_id=plaid_client_id,
                      secret=plaid_secret,
                      environment='sandbox')

def getAccessToken(user):
    user_details = User.objects.get(username=user)
    user_id = user_details.id
    token = Tokens.objects.get(user_id=user_id)
    access_token = token.access_tkn
    return access_token


def getAccountData(request):
    access_token = getAccessToken(request.user)
    context = dict()

    try:
        response = client.Auth.get(access_token)
        accounts = response['accounts']

        context = {
            'name': 'Accounts Data',
            'data': accounts,
        }

    except APIError as e:
        messages.info(request, 'APIError: Error getting accounts data')
        return redirect('users:account')
    except ItemError as e:
        messages.info(request, 'ItemError: Error getting accounts data')
        return redirect('users:account')
    except requests.Timeout:
        messages.info(request, 'Request timeout, please retry')
        return redirect('users:account')
    except InvalidInputError as e:
        messages.info(request, 'InvalidInputError: Wrong access token')
        return redirect('users:account')
    return render(request, 'showData.html', context)


def getTransactionData(request):
    access_token = getAccessToken(request.user)
    context = dict()
    try:
        response = client.Transactions.get(access_token, start_date='2020-01-01', end_date='2020-02-02')
        transactions = response['transactions']

        # the transactions in the response are paginated, so make multiple calls while increasing the offset to
        # retrieve all transactions
        while len(transactions) < response['total_transactions']:
            response = client.Transactions.get(access_token, start_date='2019-01-01', end_date='2020-01-01', offset=len(transactions))
            transactions.extend(response['transactions'])

        context = {
            'name' : 'Transactions Data',
            'data' : transactions,
        }

    except APIError as e:
        messages.info(request, 'APIError: Error getting transaction data')
        return redirect('users:account')
    except ItemError as e:
        messages.info(request, 'ItemError: Error getting transaction data')
        return redirect('users:account')
    except requests.Timeout:
        messages.info(request, 'Request timeout, please retry')
        return redirect('users:account')
    except InvalidInputError as e:
        messages.info(request, 'InvalidInputError: Wrong access token')
        return redirect('users:account')
    return render(request, 'showData.html', context)

def getAccounts(request):

    if request.method == 'POST':
        username = request.data.get('username', None)
        password = request.data.get('password', None)

        user = authenticate(request, username=username, password=password)
        access_token = getAccessToken(user)
        if access_token:
            try:
                save_accounts_data.delay(user, access_token) 
            except:
                pass
        render(request, 'userAccount.html')

def exchangeToken(public_token):
    response = client.Item.public_token.exchange(public_token)
    access_token = response['access_token']
    return access_token

def index(request):
	return render(request, 'login.html')

def signup(request):
    form = UserSignupForm()

    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('users:login')


    context = {'form': form}
    return render(request, 'signup.html', context)

def loginPage(request):
    print('login: ', request)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            user_details = User.objects.get(username=username)
            user_id = user_details.id
            try:
                token = Tokens.objects.get(user_id=user_id)
                return redirect('users:account')
            except Tokens.DoesNotExist:
                return redirect('users:home')

        else:
            messages.info(request, 'Username OR Password is incorrect')
    
    return render(request, 'login.html')


def logoutUser(request):
    logout(request)
    return redirect('users:login')


def home(request):
    if request.method == 'POST':
        public_token = request.POST.get('public_token')
        generateAccessToken(request, public_token)

    if request.user.is_authenticated:
        return render(request, 'submitToken.html')
    else:
        return redirect('users:login')

def submitToken(request):
    if request.user.is_authenticated:
        return render(request, 'submitToken.html')
    else:
        return redirect('users:login')

def generateAccessToken(request, public_token):

    try:
        access_token = exchangeToken(public_token)
        saveDetails(request, access_token)
        return redirect('users:account')
    except ItemError as e:
        #check the code attribute of the error to determine the specific error
        if e.code == 'ITEM_LOGIN_REQUIRED':
            messages.info(request, "The user's login information has changed, Generate a public token")
        else:
            messages.info(request, 'ItemError')
        return redirect('users:submitToken')
    except APIError as e:
        if e.code == 'PLANNED_MAINTENANCE':
            messages.info(request, 'Plaid is under maintenance, please try after some time')
        else:
            messages.info(request, 'APIError')
        return redirect('users:submitToken')
    except requests.Timeout:
        messages.info(request, 'Request timeout, please retry')
        return redirect('users:submitToken')
    except InvalidInputError as e:
        messages.info(request, 'provided public token is in an invalid format. expected format: public-<environment>-<identifier>')
        return redirect('users:submitToken')
    except InvalidRequestError as e:
        messages.info(request, 'public_token must be a non-empty string')
        return redirect('users:submitToken')

def account(request):
    print('account: ', request)
    if request.user.is_authenticated:
        return render(request, 'userAccount.html')
    else:
        return redirect('users:login')


def saveDetails(request, access_token):
    item_response = client.Item.get(access_token)
    institution_response = client.Institutions.get_by_id(item_response['item']['institution_id'], 'US')
    print(item_response, ' : ', institution_response)
    item_id = item_response['item']['item_id']
    webhook = item_response['item']['webhook']

    token = Tokens.objects.create(user=request.user, access_tkn=access_token, item_id=item_id, webhook=webhook)
    token.save()
    messages.info(request, 'successfully submitted public token')
   
    

banking_django_plaid-master/users/templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">



	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

<button id="link-button">Link Account</button>
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script type="text/javascript">
(async function() {
  const fetchLinkToken = async () => {
    const response = await fetch('/create_link_token', { method: 'POST' });
    const responseJSON = await response.json();
    return responseJSON.link_token;
  };
  const configs = {
    // 1. Pass a new link_token to Link.
    token: await fetchLinkToken(),
    onSuccess: async function(public_token, metadata) {
      // 2a. Send the public_token to your app server.
      // The onSuccess function is called when the user has successfully
      // authenticated and selected an account to use.
      await fetch('/get_access_token', {
        method: 'POST',
        body: JSON.stringify({ public_token: public_token }),
      });
    },
    onExit: async function(err, metadata) {
      // 2b. Gracefully handle the invalid link token error. A link token
      // can become invalidated if it expires, has already been used
      // for a link session, or is associated with too many invalid logins.
      if (err != null && err.error_code === 'INVALID_LINK_TOKEN') {
        linkHandler.destroy();
        linkHandler = Plaid.create({
          ...configs,
          token: await fetchLinkToken(),
        });
      }
      if (err != null) {
        // Handle any other types of errors.
      }
      // metadata contains information about the institution that the
      // user selected and the most recent API request IDs.
      // Storing this information can be helpful for support.
    },
  };
  var linkHandler = Plaid.create(configs);
  document.getElementById('link-button').onclick = function() {
    linkHandler.open();
  };
})();
</script>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

                </div>
                
                {% for message in messages %}
                    <p id ="">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'users:signup' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

banking_django_plaid-master/users/templates/logout.html
<h1>Logout</h1>

banking_django_plaid-master/users/templates/showData.html
<!DOCTYPE html>
<html>
    
<head>
	<title>User Account</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 100%;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


                    <h3 id="form-title">Hi {{request.user}}</h3>

				</div>
				<div class="d-flex justify-content-center form_container">
					<form >
                        <h4 id = "form-title">{{name}}</h4>
                        {{data}}
                        <div class="d-flex justify-content-center mt-3 login_container">
                            <a class="btn btn-success" href="{% url 'users:account' %}" class="ml-2">Back</a>
                        </div>

					</form>

                </div>
                
                {% for message in messages %}
                    <p id ="">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<a href="{% url 'users:logout' %}" class="ml-2">Logout</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>



banking_django_plaid-master/users/templates/signup.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                   
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
                </div>
                
                {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account?<a href="{% url 'users:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/*placeholder values in forms.py will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

banking_django_plaid-master/users/templates/submitToken.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Submit Token</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


                    <h3 id="form-title">Hi {{request.user}}</h3>

				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="text" name="public_token" placeholder="Public Token..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Submit Token">
                            </div>
                    </form>
                    
                    

                </div>
                
                {% for message in messages %}
                    <p id ="">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<a href="{% url 'users:logout' %}" class="ml-2">Logout</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

banking_django_plaid-master/users/templates/userAccount.html

<!DOCTYPE html>
<html>
    
<head>
	<title>User Account</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


                    <h3 id="form-title">Hi {{request.user}}</h3>

				</div>
				<div class="d-flex justify-content-center form_container">
					<form >
                
							<div class="d-flex justify-content-center mt-3 login_container">
                                 <!-- <button class="btn btn-success" onclick="getAccountData()">Get Account Data</button> -->
                                 <a class="btn btn-success" href="{% url 'users:getAccountData' %}" class="ml-2"">Get Account Data</a>
                            </div>
                               
                            <div class="d-flex justify-content-center mt-3 login_container">
                                <!-- <button class="btn btn-success" onclick="getTransactionData()">Get Transaction Data</button> -->
                                <a class="btn btn-success" href="{% url 'users:getTransactionData' %}" class="ml-2"">Get Transaction Data</a>
                            </div>

					</form>

                </div>
                
                {% for message in messages %}
                    <p id ="">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<a href="{% url 'users:logout' %}" class="ml-2">Logout</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

